# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikename', models.CharField(blank=True, max_length=100)),
                ('bikeid', models.CharField(blank=True, max_length=100)),
                ('bikeimage', models.ImageField(max_length=255, null=True, upload_to=b'/static/images')),
                ('rentbelow12', models.CharField(blank=True, max_length=100)),
                ('rentbelow15', models.CharField(blank=True, max_length=100)),
                ('rentmorethan15', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
