# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_bikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='bikeimage',
            field=models.ImageField(max_length=255, null=True, upload_to=b'static/images'),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='bikename',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
    ]
